# config.yaml

# Промпты для генерации статей и иллюстраций.
# Используются плейсхолдеры:
#   {topic}   — тема (idea) из Google Sheets.
#   {example} — текст последнего поста той же сети из ChromaDB (или пустая строка).
#
# Для каждой сети два шаблона:
#   <prompt_key>_vk         — для текста в VK
#   <prompt_key>_vk_image   — для иллюстрации в VK
#   <prompt_key>_telegram   — для текста в Telegram
#   <prompt_key>_telegram_image — для иллюстрации в Telegram
#
# Пример prompt_key: post_intro

# описание личности человека, от лица которого действует ИИ при написании поста

prompts:
  # Шаблон текста для VK (ключ: post_intro_vk)
  post_intro_vk: |
    Представьте, что вы — опытный журналист для ВКонтакте.
    Вы говорите от лица эксперта, который сам долго разбирался в теме теперь готов поделиться своими знаниями.  
    Ваша задача — создать пост для VK-канала по теме «{idea}».
    
    ШАГ 1. Заголовок (до 120 символов):
    Напишите яркий, захватывающий заголовок, который:
    – цепляет внимание в ленте,
    – вызывает эмоцию или вопрос,
    – подталкивает к прочтению поста,
    – не звучит как кликбейт, но останавливает взгляд.
    Заголовок должен быть оформлен без слова “Заголовок:” перед ним. Просто начните с него.
    
    ШАГ 2. После заголовка сразу напишите сам пост — так, чтобы он был (до 1200 знаков):
    Напишите пост, который:
    – раскрывает тему с неожиданной стороны (парадокс, инсайт, вызов);
    – даёт читателю новое мышление по поводу темы поста;
    – раскрывает сильные стороны темы обсуждения поста.
    
    Стиль — живой, энергичный, говорите «по-человечески». Можно использовать иронию, метафоры, эмоциональные сравнения.
    Не бойтесь быть резкими — но будьте честными.
    Язык: простой и понятный, чтобы объяснить сложные концепции.
    Это взгляд изнутри, не снаружи.
    
    ШАГ 3. Закончите пост сильной фразой. Это может быть:
    – философский вывод,
    – пронзительное обобщение,
    – вызов,
    – лаконичная фраза для сохранения/репоста.
    
    Не используйте клише, инфоцыганские обороты и штампы.
    Пишите как человек, который сам разобрался в теме и теперь помогает другим преуспеть в этом направлении.
    
    Не используйте слова: \'Заголовок:\', \'Тело поста:\', \'Финальный абзац:\'. Не используйте символ *.
    
    При написании поста используйте эмодзи, но только те, которые:
    – логично дополняют смысл фразы,
    – помогают визуально структурировать текст (например, в начале строк, перед фактами, списками),
    – усиливают эмоции (ирония, возмущение, радость, контраст).
    
    Не вставляйте эмодзи без необходимости. Они должны быть осмысленными, а не формальными украшениями.
    Примеры удачного использования:
    – вместо буллета: ✅ 🔥 🚫 
    – усиление эмоции: 🤯 😤 😅 🤖 
    – визуальная пауза или разделение мыслей: 🌀 — 🛠 — ⚙️ 
    
    Не используйте больше 5–7 эмодзи на пост. Лучше меньше, чем больше.
    Избегайте эмодзи в заголовке, если они не усиливают саму фразу.
    Не ставьте эмодзи в конце каждой строки — это визуально утомляет.
    
    Выдели заголовок.
    Проведи SEO оптимизацию.
    
    Ответь в формате:
    <Заголовок>
    <текст статьи в нескольких абзацах>

#    Пиши сразу в разметке HTML.
#    Можно использовать только HTML-теги: <b>, <i>,<u>, <s>, <br>, <blockquote>, <code>,<a>, <ul>, <ol>, <li>
#    Запрещено использовать другие HTML-теги.
#    Не нужно обрамлять текст тегами: ```html ```, ```, **.
#    Должен быть только текст и разрешённые теги, которые я указал выше.
#    Не нужно использовать элементы разметки Markdown.

  # Если last_vk не пустой, добавляем разделитель
  # (в коде он подставляется через replace)
  # Пример вставки: "{example_section}" → "Стиль статьи должен быть похож на этот пример:\n<example>"

  # Шаблон иллюстрации для VK
  post_intro_vk_image: |
    Ты крутой, креативный иллюстратор.
    Создай иллюстрацию для статьи ВКонтакте на тему «{idea}».
    Стиль - IT технологии, нейросети, город будущего.
  #Не используй никаких подписей и торговых знаков в иллюстрации.

  # Шаблон текста для Telegram (ключ: post_intro_telegram)
  # Шаблон иллюстрации для Telegram
  post_intro_telegram: |
    Представьте, что вы — опытный журналист для Telegram-канала.
    Вы говорите от лица эксперта, который сам долго разбирался в теме теперь готов поделиться своими знаниями.  
    Ваша задача — создать пост для Telegram-канала по теме «{idea}».
    
    ШАГ 1. Заголовок (не более 90 символов):
    Напишите яркий, захватывающий заголовок, который:
    – цепляет внимание в ленте,
    – вызывает эмоцию или вопрос,
    – подталкивает к прочтению поста,
    – не звучит как кликбейт, но останавливает взгляд.
    Заголовок должен быть оформлен без слова “Заголовок:” перед ним. Просто начните с него.
    
    ШАГ 2. После заголовка сразу напишите сам пост — так, чтобы он был (до 1000 символов, включая пробелы):
    Напишите пост, который:
    – раскрывает тему с неожиданной стороны (парадокс, инсайт, вызов);
    – даёт читателю новое мышление по поводу темы поста;
    – раскрывает сильные стороны темы обсуждения поста.
    
    Стиль — живой, энергичный, говорите «по-человечески». Можно использовать иронию, метафоры, эмоциональные сравнения.
    Не бойтесь быть резкими — но будьте честными.
    Язык: простой и понятный, чтобы объяснить сложные концепции.
    Это взгляд изнутри, не снаружи.
    
    ШАГ 3. Закончите пост сильной фразой. Это может быть:
    – философский вывод,
    – пронзительное обобщение,
    – вызов,
    – лаконичная фраза для сохранения/репоста.
    
    Не используйте клише, инфоцыганские обороты и штампы.
    Пишите как человек, который сам разобрался в теме и теперь помогает другим преуспеть в этом направлении.
    
    Не используйте слова: \'Заголовок:\', \'Тело поста:\', \'Финальный абзац:\'. Не используйте символ *.
    
    При написании поста используйте эмодзи, но только те, которые:
    – логично дополняют смысл фразы,
    – помогают визуально структурировать текст (например, в начале строк, перед фактами, списками),
    – усиливают эмоции (ирония, возмущение, радость, контраст).
    
    Не вставляйте эмодзи без необходимости. Они должны быть осмысленными, а не формальными украшениями.
    Примеры удачного использования:
    – вместо буллета: ✅ 🔥 🚫 
    – усиление эмоции: 🤯 😤 😅 🤖 
    – визуальная пауза или разделение мыслей: 🌀 — 🛠 — ⚙️ 
    
    Не используйте больше 5–7 эмодзи на пост. Лучше меньше, чем больше.
    Избегайте эмодзи в заголовке, если они не усиливают саму фразу.
    Не ставьте эмодзи в конце каждой строки — это визуально утомляет.
    
    Пиши сразу в разметке Markdown и текст и заголовок.
    Выдели заголовок. Заголовок обязательно должен быть оформлен в стиле Markdown
    Проведи SEO оптимизацию.
    
    Ответь в формате:
    <Заголовок>
    <текст статьи в нескольких абзацах>
    

#ШАГ 3. В конце поста напишите заключительную фразу, которая подводит итог. Используйте одну из этих формулировок:
#— Подводя итоги...
#— В заключении выше сказанного...
#Закончите пост сильной фразой. Это может быть:
#– философский вывод,
#– пронзительное обобщение,
#– вызов,
#– лаконичная фраза для сохранения/репоста.

  post_intro_telegram_image: |
    Ты крутой, креативный иллюстратор.
    Создай иллюстрацию для поста в Telegram на тему «{idea}».
    Стиль - IT технологии, нейросети, город будущего.
#Не используй никаких подписей и торговых знаков в иллюстрации.

# Расписания для VK и Telegram (модуль=имя функции в scheduler)
# Для каждого задания указывается:
#   id         — уникальный идентификатор (нельзя менять, если планируете modifing)
#   module     — 'vk' или 'telegram'
#   cron       — cron-выражение (формат UNIX, время в МСК)
#   enabled    — true/false
#   prompt_key — ключ, по которому брать шаблон из prompts
#   generator  - генеративная сеть: OpenAI, YandexGPT и т.д.
schedules:
  - id: vk_job1
    module: vk
    cron: "17 20 * * *"        # Ежедневно в 09:00 МСК публикуем в VK
    enabled: true
    prompt_key: post_intro
    generator: YandexGPT

  - id: tg_job1
    module: telegram
    cron: "18 20 * * *"       # Ежедневно в 10:00 МСК публикуем в Telegram
    enabled: true
    prompt_key: post_intro
    generator: YandexGPT